name: test_pixelfield
description: "A new Flutter project for testing pixelfield by Vazgen"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
      
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.3
  auto_route: ^9.3.0+1
  shared_preferences: ^2.5.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  auto_route_generator: ^9.3.1
  flutter_native_splash: ^2.4.4
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  image: "assets/splash/logo.png" 
  android: true 
  ios: true 
  web: true 
  android_gravity: center 
  ios_content_mode: center 
  background_image: "assets/splash/bg.png" 
  
  android_12:
    image: "assets/splash/logo.png" 
    background_image: "assets/splash/bg.png" 
    fullscreen: true
    

flutter:  
  uses-material-design: true
  assets:
    - assets/splash/logo.png
    - assets/splash/bg.png
    - assets/images/
    - assets/icons/
    - assets/mocks/
